### PR TITLE
better interop returns + improve isReviewed requirement handling

### PR DESCRIPTION
**Pull request by Hiviexd**

### CODE REVIEW

**Comment by pishifat** [comment]
can you think of another way to handle this? having something that implies all chat message things have true evalIsReviewed feels confusing

**Comment by Hiviexd** [comment]
rename to reviewStatus? it's set as true by default for stuff that doesnt need reviews

**Comment by Hiviexd** [comment]
> rename to reviewStatus? it's set as true by default for stuff that doesnt need reviews (which is basically only reports)

**Comment by Hiviexd** [comment]
also, i went about it this way cuz ur approach hides the eval preview alongside the button which makes reading feedbacks annoying, so i tried to just hide the button

**Pull request merged**
